stages:
  - build
  - deploy

build-linux:
  stage: build
  script:
    - make BUILD_TYPE=release PACKAGE_ASSETS=true

  artifacts:
    name: 'build-linux'
    expose_as: 'build linux'
    paths: ['build/bin']

  cache:
    paths:
      - "build/obj/**/*.o"
      - "build/obj/**/*.d"

build-windows:
  stage: build
  script:
    - make CXX=x86_64-w64-mingw32-g++ BUILD_TYPE=release PACKAGE_ASSETS=true

  artifacts:
    name: 'build-windows'
    expose_as: 'build windows'
    paths: ['build/bin']

  cache:
    paths:
      - "build/obj/**/*.o"
      - "build/obj/**/*.d"

build-emscripten:
  stage: build
  script:
    - source $EMSDK/emsdk_env.sh
    - make CXX=em++ BUILD_TYPE=release

  artifacts:
    name: 'build-emscripten'
    expose_as: 'build emscripten'
    paths: ['build/bin']

  cache:
    paths:
      - "build/obj/**/*.o"
      - "build/obj/**/*.d"

# --- Deploys online build

deploy-emscripten:
  stage: deploy
  needs: ['build-emscripten']
  script:
    - mkdir -p ~/public_html/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME/
    - rm -rf ~/public_html/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME/*
    - cp -r build/bin/* ~/public_html/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME/